<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>iuh.fit.fe</groupId>
        <artifactId>be_webSatLichKham</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>scheduling-service</artifactId>
    <name>scheduling-service</name>
    <description>SCHED-01..06: xếp/sửa/xóa ca làm việc, sinh khung giờ khám, yêu cầu đổi lịch của bác sĩ</description>

    <dependencies>
        <dependency>
            <groupId>iuh.fit.fe</groupId>
            <artifactId>common</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc</artifactId>
        </dependency>

        <!-- Test -->
        <dependency>
            <groupId>iuh.fit.fe</groupId>
            <artifactId>common</artifactId>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
