package iuh.fit.se.eclinic.identity.dulieumau;

import java.util.List;
import java.util.Map;

/**
 * Hồ sơ giới thiệu mẫu của các bác sĩ mẫu, theo số thứ tự trong {@link DuLieuMau#BAC_SI}. Nội dung chỉ để thử / demo.
 *
 * @param chucVu        chức vụ tại phòng khám
 * @param gioiThieuNgan 1-2 câu hiện trên thẻ bác sĩ
 * @param daoTao        quá trình đào tạo, mỗi phần tử 1 ý
 * @param congTac       quá trình công tác, mỗi phần tử 1 ý
 * @param linhVuc       khám và điều trị, mỗi phần tử 1 ý
 */
public record HoSoBacSiMau(String chucVu, String gioiThieuNgan, List<String> daoTao, List<String> congTac,
        List<String> linhVuc) {

    public static final Map<Integer, HoSoBacSiMau> THEO_SO = Map.ofEntries(
            Map.entry(1, new HoSoBacSiMau("Trưởng khoa Nội tổng quát",
                    "Tiến sĩ nội khoa với 18 năm khám và điều trị bệnh tiêu hoá, nội tiết.",
                    List.of("2001 - 2007: Bác sĩ đa khoa, Đại học Y Dược TP. Hồ Chí Minh",
                            "2008 - 2011: Thạc sĩ Nội khoa, Đại học Y Dược TP. Hồ Chí Minh",
                            "2013 - 2017: Tiến sĩ Y học, chuyên ngành Nội tiêu hoá"),
                    List.of("2007 - 2015: Bác sĩ điều trị khoa Nội tiêu hoá, bệnh viện tuyến thành phố",
                            "2015 - 2021: Phó trưởng khoa Nội tổng hợp",
                            "2021 - nay: Trưởng khoa Nội tổng quát, Phòng khám eClinic"),
                    List.of("Viêm loét dạ dày - tá tràng, trào ngược dạ dày thực quản",
                            "Đái tháo đường, bệnh tuyến giáp",
                            "Tăng huyết áp, rối loạn mỡ máu",
                            "Khám sức khoẻ tổng quát cho người lớn"))),
            Map.entry(2, new HoSoBacSiMau("Bác sĩ điều trị",
                    "Theo dõi lâu dài cho người bệnh đái tháo đường và rối loạn mỡ máu.",
                    List.of("2010 - 2016: Bác sĩ đa khoa, Đại học Y khoa Phạm Ngọc Thạch",
                            "2018 - 2020: Thạc sĩ Nội khoa, Đại học Y Dược TP. Hồ Chí Minh"),
                    List.of("2016 - 2022: Bác sĩ khoa Nội tổng hợp, bệnh viện quận",
                            "2022 - nay: Bác sĩ điều trị khoa Nội tổng quát, Phòng khám eClinic"),
                    List.of("Khám sức khoẻ tổng quát, tầm soát bệnh mạn tính",
                            "Đái tháo đường típ 2, tiền đái tháo đường",
                            "Rối loạn mỡ máu, gan nhiễm mỡ",
                            "Tư vấn dinh dưỡng và thay đổi lối sống"))),
            Map.entry(3, new HoSoBacSiMau("Trưởng khoa Nhi",
                    "20 năm chăm sóc trẻ em, chuyên về bệnh hô hấp và dinh dưỡng.",
                    List.of("1999 - 2005: Bác sĩ đa khoa, Đại học Y Dược TP. Hồ Chí Minh",
                            "2007 - 2009: Bác sĩ chuyên khoa I Nhi khoa",
                            "2012 - 2014: Bác sĩ chuyên khoa II Nhi khoa"),
                    List.of("2005 - 2016: Bác sĩ khoa Hô hấp, bệnh viện nhi tuyến thành phố",
                            "2016 - 2020: Phó trưởng khoa Nội tổng hợp nhi",
                            "2020 - nay: Trưởng khoa Nhi, Phòng khám eClinic"),
                    List.of("Viêm phế quản, viêm phổi, hen phế quản ở trẻ em",
                            "Suy dinh dưỡng, biếng ăn, chậm tăng cân",
                            "Sốt, tiêu chảy và các bệnh nhiễm khuẩn thường gặp",
                            "Tư vấn dinh dưỡng theo lứa tuổi"))),
            Map.entry(4, new HoSoBacSiMau("Bác sĩ điều trị",
                    "Khám nhi tổng quát, tư vấn tiêm chủng và theo dõi phát triển của trẻ.",
                    List.of("2011 - 2017: Bác sĩ đa khoa, Đại học Y khoa Phạm Ngọc Thạch",
                            "2019 - 2021: Bác sĩ chuyên khoa I Nhi khoa"),
                    List.of("2017 - 2022: Bác sĩ khoa Nhi, bệnh viện quận",
                            "2022 - nay: Bác sĩ điều trị khoa Nhi, Phòng khám eClinic"),
                    List.of("Khám sức khoẻ định kỳ cho trẻ sơ sinh và trẻ nhỏ",
                            "Tư vấn lịch tiêm chủng",
                            "Theo dõi chiều cao, cân nặng, phát triển vận động",
                            "Bệnh hô hấp và tiêu hoá thường gặp ở trẻ"))),
            Map.entry(5, new HoSoBacSiMau("Trưởng khoa Da liễu",
                    "Điều trị mụn trứng cá, viêm da cơ địa, vảy nến và bệnh da dị ứng.",
                    List.of("2007 - 2013: Bác sĩ đa khoa, Đại học Y Dược TP. Hồ Chí Minh",
                            "2015 - 2017: Thạc sĩ Da liễu, Đại học Y Dược TP. Hồ Chí Minh"),
                    List.of("2013 - 2020: Bác sĩ điều trị, bệnh viện chuyên khoa da liễu",
                            "2020 - nay: Trưởng khoa Da liễu, Phòng khám eClinic"),
                    List.of("Mụn trứng cá và sẹo mụn",
                            "Viêm da cơ địa, chàm, mề đay",
                            "Vảy nến, bạch biến",
                            "Bệnh da dị ứng do thuốc, mỹ phẩm"))),
            Map.entry(6, new HoSoBacSiMau("Bác sĩ điều trị",
                    "Khám da liễu tổng quát, tư vấn chăm sóc da và điều trị nấm da.",
                    List.of("2014 - 2020: Bác sĩ đa khoa, Đại học Y khoa Phạm Ngọc Thạch",
                            "2021: Chứng chỉ định hướng chuyên khoa Da liễu"),
                    List.of("2020 - 2023: Bác sĩ khoa Da liễu, bệnh viện quận",
                            "2023 - nay: Bác sĩ điều trị khoa Da liễu, Phòng khám eClinic"),
                    List.of("Nấm da, lang ben, hắc lào",
                            "Viêm da tiếp xúc, viêm da tiết bã",
                            "Tư vấn chăm sóc da theo loại da",
                            "Mụn cóc, mụn thịt"))),
            Map.entry(7, new HoSoBacSiMau("Trưởng khoa Tai Mũi Họng",
                    "Nội soi và điều trị viêm xoang mạn tính, viêm tai giữa, viêm amidan.",
                    List.of("2003 - 2009: Bác sĩ đa khoa, Đại học Y Dược TP. Hồ Chí Minh",
                            "2011 - 2013: Bác sĩ chuyên khoa I Tai Mũi Họng",
                            "2016 - 2018: Bác sĩ chuyên khoa II Tai Mũi Họng"),
                    List.of("2009 - 2019: Bác sĩ điều trị, bệnh viện chuyên khoa tai mũi họng",
                            "2019 - nay: Trưởng khoa Tai Mũi Họng, Phòng khám eClinic"),
                    List.of("Viêm mũi xoang cấp và mạn tính",
                            "Viêm tai giữa, ù tai, giảm thính lực",
                            "Viêm amidan, viêm VA",
                            "Nội soi tai mũi họng"))),
            Map.entry(8, new HoSoBacSiMau("Bác sĩ điều trị",
                    "Khám tai mũi họng cho người lớn và trẻ em, điều trị viêm mũi dị ứng.",
                    List.of("2012 - 2018: Bác sĩ đa khoa, Đại học Y khoa Phạm Ngọc Thạch",
                            "2020 - 2022: Bác sĩ chuyên khoa I Tai Mũi Họng"),
                    List.of("2018 - 2023: Bác sĩ khoa Tai Mũi Họng, bệnh viện quận",
                            "2023 - nay: Bác sĩ điều trị khoa Tai Mũi Họng, Phòng khám eClinic"),
                    List.of("Viêm mũi dị ứng",
                            "Viêm họng, viêm thanh quản",
                            "Lấy ráy tai, dị vật tai mũi họng",
                            "Bệnh tai mũi họng ở trẻ em"))),
            Map.entry(9, new HoSoBacSiMau("Cố vấn chuyên môn Tim mạch",
                    "Phó giáo sư với 25 năm trong chuyên ngành tim mạch, chuyên về tăng huyết áp và bệnh mạch vành.",
                    List.of("1994 - 2000: Bác sĩ đa khoa, Đại học Y Dược TP. Hồ Chí Minh",
                            "2002 - 2005: Thạc sĩ Nội tim mạch",
                            "2007 - 2011: Tiến sĩ Y học, chuyên ngành Nội tim mạch",
                            "2018: Được phong hàm Phó giáo sư"),
                    List.of("2000 - 2012: Bác sĩ điều trị khoa Tim mạch, bệnh viện tuyến trung ương",
                            "2012 - 2022: Trưởng khoa Nội tim mạch",
                            "2022 - nay: Cố vấn chuyên môn Tim mạch, Phòng khám eClinic"),
                    List.of("Tăng huyết áp",
                            "Bệnh mạch vành, đau thắt ngực",
                            "Suy tim, rối loạn nhịp tim",
                            "Siêu âm tim, điện tâm đồ"))),
            Map.entry(10, new HoSoBacSiMau("Trưởng khoa Sản phụ khoa",
                    "Khám thai, siêu âm sản khoa và điều trị các bệnh phụ khoa thường gặp.",
                    List.of("2005 - 2011: Bác sĩ đa khoa, Đại học Y Dược TP. Hồ Chí Minh",
                            "2013 - 2015: Thạc sĩ Sản phụ khoa, Đại học Y Dược TP. Hồ Chí Minh"),
                    List.of("2011 - 2021: Bác sĩ điều trị, bệnh viện chuyên khoa phụ sản",
                            "2021 - nay: Trưởng khoa Sản phụ khoa, Phòng khám eClinic"),
                    List.of("Khám thai định kỳ, siêu âm thai",
                            "Viêm nhiễm phụ khoa",
                            "Rối loạn kinh nguyệt, u xơ tử cung",
                            "Tư vấn kế hoạch hoá gia đình"))),
            Map.entry(11, new HoSoBacSiMau("Trưởng khoa Mắt",
                    "Khám tật khúc xạ, điều trị viêm kết mạc và tư vấn phẫu thuật đục thuỷ tinh thể.",
                    List.of("2009 - 2015: Bác sĩ đa khoa, Đại học Y khoa Phạm Ngọc Thạch",
                            "2017 - 2019: Bác sĩ chuyên khoa I Nhãn khoa"),
                    List.of("2015 - 2022: Bác sĩ điều trị, bệnh viện chuyên khoa mắt",
                            "2022 - nay: Trưởng khoa Mắt, Phòng khám eClinic"),
                    List.of("Cận thị, viễn thị, loạn thị",
                            "Viêm kết mạc, khô mắt",
                            "Đục thuỷ tinh thể, tăng nhãn áp",
                            "Khám mắt cho trẻ em"))),
            Map.entry(12, new HoSoBacSiMau("Trưởng khoa Răng Hàm Mặt",
                    "Khám và điều trị răng miệng tổng quát, nha khoa trẻ em.",
                    List.of("2013 - 2019: Bác sĩ Răng Hàm Mặt, Đại học Y Dược TP. Hồ Chí Minh",
                            "2021: Chứng chỉ Nha khoa trẻ em"),
                    List.of("2019 - 2023: Bác sĩ điều trị, phòng khám nha khoa",
                            "2023 - nay: Trưởng khoa Răng Hàm Mặt, Phòng khám eClinic"),
                    List.of("Trám răng, điều trị tuỷ",
                            "Nhổ răng, lấy cao răng",
                            "Nha khoa trẻ em",
                            "Tư vấn chỉnh nha"))));

}
